'use client'
import type { Metadata } from "next";
import { SessionProvider } from 'next-auth/react'
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Kada GPT",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
        <body>
          <SessionProvider>
          {children}
        </SessionProvider>
        </body>
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  );
}
