services:
  jupyterlab:
    build:
      context: ./jupyterlab
      dockerfile: Dockerfile
    container_name: jupyterlab
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    expose:
      - "8888"
    ports:
      - "8888:8888"
    volumes:
      - ./jupyterlab/settings:/root/.jupyter
      - ./workspace:/workspace
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - qdrant
    networks:
      - kada-gpt

  qdrant:
    image: qdrant/qdrant:v1.5.0
    container_name: qdrant
    restart: always
    volumes:
      - ./qdrant/storage:/qdrant/storage
      - ./qdrant/snapshots:/qdrant/snapshots
    networks:
      - kada-gpt

networks:
  kada-gpt:
    name: kada-gpt
    driver: bridge
