services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - app-vscode-server:/app/.vscode-server
      # - app-vscode:/vscode
      - node_modules:/app/node_modules
      - ./chat:/app
    ports:
      - 3000:3000
    env_file:
      - .env.dev
    tty: true
    stdin_open: true
    networks:
      - kada-gpt-front

volumes:
  node_modules:
  app-vscode-server:
  # app-vscode:

networks:
  kada-gpt-front:
    name: kada-gpt-front
    driver: bridge
