services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_START_OPTION: ${NEXT_START_OPTION}
    command: >
      /bin/sh -c '
      yarn build &&
      yarn start -H 0.0.0.0
      '
    container_name: app
    volumes:
      - node_modules:/app/node_modules
      - ./chat:/app
    restart: always
    env_file:
      - ./chat/.env
      - ./chat/.env.local
      - ./chat/.env.production
    tty: true
    stdin_open: true
    networks:
      - kada-gpt
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '10'
    extra_hosts:
      - "${FQDN}:172.18.0.121"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=3000"

  auth:
    image: quay.io/keycloak/keycloak:24.0
    container_name: auth
    entrypoint: ["/opt/keycloak/bin/kc.sh","start-dev","--import-realm"]
    environment:
      TZ: "Asia/Tokyo"
      KC_DB: "mariadb"
      KC_DB_URL: "jdbc:mariadb://auth-db:3306/keycloak"
      KC_DB_USERNAME: "root"
      KC_PROXY_HEADERS: "xforwarded"
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "hogehoge"
      KC_HOSTNAME_PATH: "/keycloak"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_RELATIVE_PATH: "/keycloak"
      KC_HTTP_ENABLED: "true"
      JAVA_OPTS_APPEND: "-Xms64m -Xmx512m"
    volumes:
      - ./auth/providers:/opt/keycloak/providers
      - ./auth/themes:/opt/keycloak/themes
      - ./auth/import:/opt/keycloak/data/import
      - ./auth/init:/opt/keycloak/data/init
    env_file:
      - ./chat/.env
      - ./chat/.env.local
      - ./chat/.env.production
    networks:
      kada-gpt:
        ipv4_address: 172.18.0.120
    restart: always
    depends_on:
      - auth-db
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '10'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak-admin.rule=Host(`${FQDN}`)&&PathPrefix(`/keycloak/admin`)"
      - "traefik.http.routers.keycloak-admin.entrypoints=web"
      - "traefik.http.routers.keycloak.rule=Host(`${FQDN}`)&&PathPrefix(`/keycloak`)"
      - "traefik.http.routers.keycloak.entrypoints=web"

  auth-db:
    image: mariadb:10.11.6-jammy  # ltsを選択
    container_name: auth-db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # rootアカウントをパスワードなしで作成
      MYSQL_DATABASE: 'keycloak'
      TZ: 'Asia/Tokyo'  # タイムゾーンを日本時間に設定
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  # 文字コードを指定
    volumes:
      - auth-mysql:/var/lib/mysql
    networks:
      - kada-gpt
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '10'

  traefik:
    image: traefik:2.11.2
    container_name: traefik
    restart: always
    networks:
      kada-gpt:
        ipv4_address: 172.18.0.121
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/conf/static/traefik.yml:/etc/traefik/traefik.yml #静的設定ファイル
      - ./traefik/conf/dynamic/:/etc/traefik/dynamic-conf/         #動的設定ファイル
      - ./traefik/letsencrypt:/etc/letsencrypt
      - ./traefik/cert:/etc/my-cert
    env_file:
      - ./chat/.env
      - ./chat/.env.local
      - ./chat/.env.production
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Tokyo

volumes:
  node_modules:
  auth-mysql:

networks:
  kada-gpt:
    name: kada-gpt
    driver: bridge
    external: true
