services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
      args:
        NEXT_START_OPTION: ${NEXT_START_OPTION}
    container_name: app
    volumes:
      - app-vscode-server:/app/.vscode-server
      - node_modules:/app/node_modules
      - ./chat:/app
    ports:
      - 3000:3000
    env_file:
      - ./chat/.env
      - ./chat/.env.development
      - ./chat/.env.local
    tty: true
    stdin_open: true
    networks:
      - kada-gpt

  auth:
    image: quay.io/keycloak/keycloak:24.0
    container_name: auth
    entrypoint: ["/opt/keycloak/bin/kc.sh","start-dev","--import-realm"]
    environment:
      TZ: "Asia/Tokyo"
      KC_DB: "mariadb"
      KC_DB_URL: "jdbc:mariadb://auth-db:3306/keycloak"
      KC_DB_USERNAME: "root"
      KC_PROXY_HEADERS: "xforwarded"
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "hogehoge"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8081"
      JAVA_OPTS_APPEND: "-Xms64m -Xmx512m"
      TEST_HOGE: "hoge"
    volumes:
      - ./auth/providers:/opt/keycloak/providers
      - ./auth/themes:/opt/keycloak/themes
      - ./auth/import:/opt/keycloak/data/import
      - ./auth/init:/opt/keycloak/data/init
    env_file:
      - ./chat/.env
      - ./chat/.env.development
      - ./chat/.env.local
    networks:
      - kada-gpt
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - auth-db

  auth-db:
    image: mariadb:10.11.6-jammy  # ltsを選択
    container_name: auth-db
    restart: on-failure:2  # エラー時に再起動(2回まで)
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # rootアカウントをパスワードなしで作成
      MYSQL_DATABASE: 'keycloak'
      TZ: 'Asia/Tokyo'  # タイムゾーンを日本時間に設定
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  # 文字コードを指定
    volumes:
      - auth-mysql:/var/lib/mysql
    networks:
      - kada-gpt

volumes:
  node_modules:
  app-vscode-server:
  auth-mysql:

networks:
  kada-gpt:
    name: kada-gpt
    driver: bridge
    external: true
