# 参考 https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/next-app/dev.Dockerfile

FROM node:20-bullseye-slim

WORKDIR /app

# 存在するパッケージマネージャに基づいて依存関係をインストールする
COPY chat/package.json chat/yarn.lock* chat/package-lock.json* chat/pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
  # ローカルにNode.jsがインストールされていなくても動作するように，lockfileなしでインストールできるようにする．
  else echo "Warning: Lockfile not found. It is recommended to commit lockfiles to version control." && yarn install; \
  fi

# COPY chat/app ./app
# COPY chat/pages ./pages
# COPY chat/src ./src
# COPY chat/public ./public
# COPY chat/next.config.mjs chat/tsconfig.json chat/.eslintrc.json chat/postcss.config.mjs chat/tailwind.config.ts ./

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
ARG NEXT_TELEMETRY_DISABLED=1
ENV NEXT_TELEMETRY_DISABLED=$NEXT_TELEMETRY_DISABLED

# Note: Don't expose ports here, Compose will handle that for us

# Start Next.js in development mode based on the preferred package manager
CMD \
  if [ -f yarn.lock ]; then yarn dev; \
  elif [ -f package-lock.json ]; then npm run dev; \
  elif [ -f pnpm-lock.yaml ]; then pnpm dev; \
  else npm run dev; \
  fi
